### ISSUE TITLE
Make column selection code completion context sensitive

### ISSUE THREAD

**Issue by noahjgreen295** [AltimateAI/vscode-dbt-power-user#890] opened 2024-02-07 19:15 UTC
### Describe the feature

Right now, when you are selecting from a model or CTE, all column names in the entire project appear in the dropdown. It would be great to limit them to only the columns available from the model or CTE.

### Describe alternatives you've considered

I start typing immediately after a `select`. A dropdown appears but it lists every single column in the project. It should be narrowed to just what columns would be available at this point in the query. This could be done with dbt metadata. 

### Who will benefit?

All users will benefit as they will be able to select columns much more quickly, by only seeing the columns that are available to them at the point of the query.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment] 2024-09-17 22:01
Duplicate of https://github.com/AltimateAI/vscode-dbt-power-user/issues/79

**Closed by mdesmet** 2024-09-17 22:01 UTC
Labels: enhancement
