### ISSUE TITLE
add the possibility to configure the target when using execute SQL

### ISSUE THREAD

**Issue by greghor** [AltimateAI/vscode-dbt-power-user#1075] opened 2024-04-19 17:18 UTC
### Describe the feature

Similarly to what is possible with `dbt build` and `dbt run`, I would like to be able to configure the target for query that are executed in vscode 

<img width="909" alt="image" src="https://github.com/AltimateAI/vscode-dbt-power-user/assets/16280126/5f4d0be7-e699-4015-9b1e-4dadd5ea4892">

### Describe alternatives you've considered

Today I need to execute the model with the desired target, and go check the data in the datawarehouse UI (bigquery in my case) which is tedious and time consuming. 

### Who will benefit?

Anybody that works with at least two distinct dbt environments, typically dev and prod

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment] 2024-09-17 19:38
Duplicate of https://github.com/AltimateAI/vscode-dbt-power-user/issues/1106

**Closed by mdesmet** 2024-09-17 19:38 UTC
Labels: enhancement

**Comment by anandgupta42** [comment] 2024-09-19 19:04
This feature was introduced in version 0.45.0. You can modify the target in the bottom panel next to the "defer" status icon.This feature was introduced in version 0.45.0. You can modify the target in the bottom panel next to the "defer" status icon.
![Screenshot 2024-09-19 at 11 58 43 AM](https://github.com/user-attachments/assets/04421ac2-1720-4315-90ed-39b9e58f1780)
