### ISSUE TITLE
Forced to select a single Python interpreter on setup even when using multiple workspace folders

### ISSUE THREAD

**Issue by matthias-fbi** [AltimateAI/vscode-dbt-power-user#1078] opened 2024-04-22 10:08 UTC
### Expected behavior

Extension uses the Python interpreter +dbt version from the .venv in each workspace folder

### Actual behavior

On setup I'm forced to select a single Python interpreter which is then used for all workspace projects

### Steps To Reproduce

1. Install "Power User for dbt Core" extension
2. setup extension as shown here: https://docs.myaltimate.com/setup/reqdConfig/#use-the-setup-wizard-for-configuration-recommended
3. no option to select "use Python interpreter from the virtual environment of each workspace with a dbt project"

### Operating System

Windows 11

### dbt version

depends on the workspace

### dbt Adapter

depends on the workspace

### dbt Power User version

0.38.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment] 2024-09-17 19:41
Duplicate of https://github.com/AltimateAI/vscode-dbt-power-user/issues/770

**Closed by mdesmet** 2024-09-17 19:41 UTC
Labels: bug
