### ISSUE TITLE
Add the ability to specify target for compliation of models

### ISSUE THREAD

**Issue by jwisdom-harrys** [AltimateAI/vscode-dbt-power-user#124] opened 2022-09-13 19:36 UTC
Currently there is no way to specify the `--target` flag for compilation of models using this plugin e.g. `dbt compile --target foo --model my_model`. A plugin config flag would be ideal for this, or maybe extending the `Run Command Additional params` config flag to apply to the compile command as well.

Current workaround is to change `target` value in `profiles.yml` every time you want to compile against a different target.

# Version Info
dbt version: 1.0.8
dbt power user version: 0.6.2
VS Code version: 1.69.1
Running inside of a remote container using python:3.8.5

**Comment by mdesmet** [comment] 2024-09-17 19:45
Duplicate of https://github.com/AltimateAI/vscode-dbt-power-user/issues/1106

**Closed by mdesmet** 2024-09-17 19:45 UTC
Labels: enhancement

**Comment by anandgupta42** [comment] 2024-09-19 19:04
This feature was introduced in version 0.45.0. You can modify the target in the bottom panel next to the "defer" status icon.This feature was introduced in version 0.45.0. You can modify the target in the bottom panel next to the "defer" status icon.
![Screenshot 2024-09-19 at 11 58 43 AM](https://github.com/user-attachments/assets/04421ac2-1720-4315-90ed-39b9e58f1780)
