### ISSUE TITLE
Allow to cancel the preview query

### ISSUE THREAD

**Issue by OneCyrus** [AltimateAI/vscode-dbt-power-user#870] opened 2024-01-30 19:00 UTC
### Describe the feature

sometimes a query takes much longer than expected and there's no way to cancel the preview query. it would be great to have the option to cancel the query instead of waiting for minutes/hours until it finishes.

### Describe alternatives you've considered

restarting vscode

### Who will benefit?

engineers who are creating a new query and test it in vscode

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by malow106** [comment] 2024-02-12 16:06
Yes, I really need this feature too !

**Comment by anandgupta42** [comment] 2024-02-17 04:13
@malow106 @OneCyrus We have rolled this fix in the latest pre-release version (v0.34.0). Please try it out and let me know if you have any feedback.

Just in case if you need, here is how to Install the Pre-Release:
- Navigate to the extension page within VSCode.
- Select "Switch to Pre-Release" or access the drop-down menu/cogwheel next to the install/uninstall buttons.
- Choose 'Install Pre-Release' from the available options.

**Comment by tdeenes** [comment] 2024-02-18 22:31
duplicate of #579

**Closed** 2024-02-22 05:56 UTC
Labels: enhancement
