### ISSUE TITLE
provide a way for user to pick target profiles

### ISSUE THREAD

**Issue by anandgupta42** [AltimateAI/vscode-dbt-power-user#707] opened 2023-11-09 17:11 UTC
### Describe the feature
provide a way for user to pick target profiles
### Are you willing to submit PR?
- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment] 2024-09-17 20:02
Duplicate of https://github.com/AltimateAI/vscode-dbt-power-user/issues/1106

**Closed by mdesmet** 2024-09-17 20:02 UTC
Labels: enhancement

**Comment by anandgupta42** [comment] 2024-09-19 19:04
This feature was introduced in version 0.45.0. You can modify the target in the bottom panel next to the "defer" status icon.This feature was introduced in version 0.45.0. You can modify the target in the bottom panel next to the "defer" status icon.
![Screenshot 2024-09-19 at 11 58 43 AM](https://github.com/user-attachments/assets/04421ac2-1720-4315-90ed-39b9e58f1780)
