### ISSUE TITLE
An error occurred while loading view

### ISSUE THREAD

**Issue by 8513421** [AltimateAI/vscode-dbt-power-user#1334] opened 2024-07-25 09:30 UTC
### Expected behavior

Working extension

### Actual behavior

After reinstalling Linux Manjaro, I installed Code and the extension: Power User for dbt core. Unfortunately, it seems that it doesn't detect dbt (it is installed in venv/poetry). In the "query result" tab (after clicking play), I get: An error occurred while loading view: dbtPowerUser.PreviewResults. When selecting "compiled dbt preview," I get: still loading dbt project, please try again later... When selecting "collect diagnostic," I get: Diagnostics started...
Diagnostics ended with error...
Error=TypeError: Cannot read properties of undefined (reading 'getEnvVars')

### Steps To Reproduce

+ install Code on Manajro linux
+ install extension

### Operating System

Linux Manjaro

### dbt version

1.8.4

### dbt Adapter

postgres

### dbt Power User version

v0.42.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kalebkemp** [comment] 2024-08-14 14:47
I am having the same issue after updating VSCode this morning. Extension was working before the update.

**Comment by thebroberts** [comment] 2024-08-30 18:16
this should be fixed now:
https://github.com/AltimateAI/vscode-dbt-power-user/commit/7c26b3561fb2affd286aa1b8d3bbd00c34c1226e
#1379

**Comment by 8513421** [comment] 2024-09-05 17:40
> this should be fixed now: [7c26b35](https://github.com/AltimateAI/vscode-dbt-power-user/commit/7c26b3561fb2affd286aa1b8d3bbd00c34c1226e) #1379

Still not working on version v0.44.7

**Comment by anandgupta42** [comment] 2024-09-05 17:44
@8513421 What's the version of dbt you are using?

**Comment by 8513421** [comment] 2024-09-06 08:07
> @8513421 What's the version of dbt you are using?

dbt-core = "^1.8.4"
dbt-postgres = "^1.8.2"

**Comment by ishani2412** [comment] 2024-09-09 10:45
Same here. Dbt power user is not working in vscode on Mac M3.

**Comment by keith-fajardo** [comment] 2024-09-09 13:07
Same here. Not working when I upgraded dbt to 1.8.6

**Comment by anandgupta42** [comment] 2024-09-09 15:10
Hey @keith-fajardo, @ishani2412, @mickaelandrieu, we haven't been able to identify the root cause of this issue. Since the extension isn't loading, we're unable to generate the diagnostics or logs that typically help us resolve the problems. Can one of you ping reach out here : https://app.myaltimate.com/contactus ?

**Comment by mickaelandrieu** [comment] 2024-09-09 22:37
Hi @anandgupta42, sorry but I don't this you're right? I'm using vs code 1.93 and the VS Code Python extension is installed, enabled and up to date.

![Capture](https://github.com/user-attachments/assets/c2459f76-2c3c-487c-a3c1-11a6058ad6ce)
![Capture](https://github.com/user-attachments/assets/83c44c7e-e4c5-4854-b95c-6e722f4d1b6f)

Let me know what I can do to help you ... to help us ^^

**Comment by anandgupta42** [comment] 2024-09-09 23:07
@mickaelandrieu Can you 

1. ctrl + shift + p
2. developer: toggle developer tools
3. go to console
4. Check if you see any errors in there or share the entire log with us here at https://app.myaltimate.com/contactus ?

**Comment by ishani2412** [comment] 2024-09-10 08:10
Yes, this thing helped me in identifying the error. I was on older version
and updating to 1.93 helped in running the extension.

**Comment by mickaelandrieu** [comment] 2024-09-16 07:50
hi @anandgupta42,
thanks for the instructions.

Here are the errors I get from my console log :

![error](https://github.com/user-attachments/assets/898bfb69-3d91-4443-86eb-31f9a24288a2)

I have never installed Python using Windows Gallery/Store, I use the msi file from python project website.

Regards

**Comment by GerritPlehn** [comment] 2024-09-16 12:24
Hey all. You may want to try and use `> Python: Select Interpreter` in VSCode to change the interpreter. That helped in my case. Please take note of what the current setting is, it may help in debugging the issue.

**Comment by mickaelandrieu** [comment] 2024-09-16 13:28
I love you @GerritPlehn : this is exactly what I needed in order to fix my bug.

Thanks all for your time 👍

**Comment by mdesmet** [comment] 2024-09-17 17:37
Indeed errors are caused by setting an invalid Python interpreter. No errors should be logged in this case (this has been resolved in recent releases).

**Closed by mdesmet** 2024-09-17 17:37 UTC
Labels: bug

**Comment by anandgupta42** [comment] 2024-09-17 17:38
Thanks @mickaelandrieu for sharing the screenshot. It helped us identify the issue. A fix has been pushed and released.
