### ISSUE TITLE
Lineage not working correctly with versioned models

### ISSUE THREAD

**Issue by wahlrkr** [AltimateAI/vscode-dbt-power-user#1428] opened 2024-09-20 09:25 UTC
### Expected behavior

The DBT model should be valid and the lineage displayed

### Actual behavior

When using versioned models via https://docs.getdbt.com/docs/collaborate/govern/model-versions DBT interprets filenames from e.g. `schema.yml/model.yml/<any_yml_with_models_block>` file via the versions, not from the actual model names (i.e. joins them). This breaks DBT Power Users lineage graph by giving the warning `A valid dbt file (model, seed etc.) needs to be open and active in the editor area above to view lineage` and an empty graph even though that model is valid DBT model.

### Steps To Reproduce

This should be reproducible by 

1. Create two models `a_v1.sql` and `b_v1.sql` with some simple working SQL
2. Create `models.yml` with
```
---
version: 2
models:
  - name: a
    latest_version: 1
    versions:
      - v: 1
   - name: b_v1
```
3. Focus VSCode into `a_v1.sql` and then `b_v1.sql`

The `a` will fail to render as lineage node, but `b` is alright

### Log output/Screenshots

`A valid dbt file (model, seed etc.) needs to be open and active in the editor area above to view lineage`

### Operating System

MacOS 14.6.1

### dbt version

1.8.6

### dbt Adapter

Redshift

### dbt Power User version

v0.45.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment] 2024-09-21 04:18
Duplicate of https://github.com/AltimateAI/vscode-dbt-power-user/issues/709

**Closed by mdesmet** 2024-09-21 04:18 UTC
Labels: bug

**Comment by anandgupta42** [comment] 2024-09-25 04:43
hey @ellipsis-dev can you implement this?
